FROM infiniteproject/icecast:latest

# Copy entrypoint script
COPY icecast-entrypoint.sh /usr/local/bin/icecast-entrypoint.sh
RUN chmod +x /usr/local/bin/icecast-entrypoint.sh

# Copy base config and YP snippet
COPY icecast-base.xml /etc/icecast-base.xml
COPY icecast-yp-snippet.xml /etc/icecast-yp-snippet.xml

ENTRYPOINT ["/usr/local/bin/icecast-entrypoint.sh"]
